#!/bin/bash

# Визначаємо шлях до файлу
FILE="/etc/systemd/system.conf"

# Перевіряємо, чи є закоментована строка в файлі
if sudo grep -q '^#RuntimeWatchdogSec=' "$FILE"; then
    # Заміна закоментованої строки на нову
    sudo sed -i 's/^#RuntimeWatchdogSec=.*/RuntimeWatchdogSec=16/' "$FILE"
    echo "Строка замінена на RuntimeWatchdogSec=16."
else
    # Якщо строка не знайдена, додаємо нову в кінець файлу
    echo "RuntimeWatchdogSec=16" | sudo tee -a "$FILE" > /dev/null
    echo "Закоментована строка не знайдена. Додано RuntimeWatchdogSec=16 в кінець файлу."
fi

# Виводимо повідомлення про успішне виконання
echo "Зміни внесені успішно!"
